### ISSUE TITLE
Missing or wrong access token from glot.io

### ISSUE THREAD

**Issue by md-abdul-halim-rafi** [itaditya/Code-Runner#30]
I apologize for creating this issue here. 

I am getting a Missing or wrong access token even if my token is correct. How can I solve this issue? Please help

![](https://user-images.githubusercontent.com/54027196/99877293-30dbf400-2c27-11eb-994c-c8a4d830bd21.png)

**Comment by itaditya** [comment]
Try running this exact code on the command line but only change the token to yours. I tried today it worked.

https://github.com/prasmussen/glot-run/blob/master/api_docs/run.md#run-code-1

**Comment by itaditya** [comment]
I noticed the typo in your screenshot. It's **Token** not **Tokoen**. Also once it starts working, make a new token so spammers can't use this token and exhaust your quota.

**Comment by md-abdul-halim-rafi** [comment]
Thanks a ton for your kind response. I've got my mistake.
